spring:
  application:
    name: demo-applicant
  datasource:
    url: jdbc:mysql://dbmysqlrsld.mysql.database.azure.com:3306/testdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: adminrsld
    password: Santrsld$.$
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
springdoc:
  api-docs:
    path: /applicant-management/v1/api-docs
  swagger-ui:
    path: /swagger-ui.html