spring:
  application:
    name: demo-applicant
  datasource:
    url: jdbc:mysql://dbmysqlrsld.mysql.database.azure.com:3306/testdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${USER_DATABASE_MYSQL}
    password: ${PASS_DATABASE_MYSQL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
springdoc:
  api-docs:
    path: /applicant-management/v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
logging.level:
  org.springframework.web: DEBUG
  org.hibernate: ERROR