spring:
  application:
    name: demo-applicant
  datasource:
    url: jdbc:mysql://dbmysqlrsld.mysql.database.azure.com:3306/testdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${USER_DATABASE_MYSQL}
    password: ${PASS_DATABASE_MYSQL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: 192.168.174.130
    port: 5672
    username: user
    password: pass
application:
  security:
    jwt:
      secret-key: ${APP_JWT_SECRET_KEY}
      expiration: 300000
      refresh-token:
        expiration: 1200000
springdoc:
  api-docs:
    path: /swagger-ui/api-docs
logging.level:
  org.springframework.web: DEBUG
  org.hibernate: ERROR